@startuml
'https://plantuml.com/sequence-diagram

class InventoryTrackerApp {
    start()
    main()
    stop()
}

class MainWindowControllers {
    - myInventory: InventoryList

    tableView: TableView<Item>
    serialNumber: TableColumn<Item, String>
    name: TableColumn<Item, String>
    price: TableColumn<Item, String>

    removeButton: ImageView
    addButton: ImageView

    remainingCapacity: Label
    searchField: TextField

    + quitButtonClicked()
    + removeButtonClicked()
    + addButtonClicked()
    + saveAsTSV()
    + saveAsHTML()
    + saveAsJSON()
    + openInventory()
    + initialize()
    + getItems()
}

class AddItemWindowController {
    LETTERS: char[]
    SPECIAL_CHARACTERS: char[]

    submit: Button
    itemName: TextField
    serialNum: TextField
    itemPrice: TextField

    + submitButtonClicked()
}

class Item {
        - serialNumber: String
        - price: String
        - name: String

        + Item()
        + getSerialNumber()
        + setSerialNumber()
        + getPrice()()
        + setPrice()
        + getName()
        + setName()()
        + toString()
        + toTSV()
}

class InventoryList {
    - name: String
    - capacity: int
    + count: int
    + items: ArrayList<Item>

    + InventoryList()
    + getName()
    + setName()
    + getRemainingCapacity()
    + setCapacity()
    + updateName()
    + addItem()
    + removeItem()
    + editName()
    + editSerialNumber()
    + editPrice()
    + getItems()
}


javafx.Application <|-- InventoryTrackerApp
InventoryTrackerApp -- MainWindowControllers
MainWindowControllers -- AddItemWindowController
MainWindowControllers - Item
AddItemWindowController - Item
Item -- InventoryList

@enduml